name: Playwright Tests

on:
  repository_dispatch:
    types: [trigger-playwright-tests]  # Name of the event type sent from Hexo

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps  # Install all Playwright dependencies and browsers

    - name: Run Playwright Tests
      run: npx playwright test
